### ISSUE TITLE
platinum-missing-data

### ISSUE THREAD

**Issue by MicheleStoltz** [domtronn/nuzlocke.app#119]
**Describe the bug**

**To Reproduce**
1. Go to 'https://nuzlocke.app/guides/platinum'
4. All the data is missing

**Expected behavior**
https://nuzlocke.app/guides/platinum should contain the data that is present in other rom's, in terms of gym max levels etc.

**Comment by domtronn** [comment]
Hey @MicheleStoltz this is due to some rehosting I did a few weeks back - long store short, the hosting provider deleted old, cached assets for the site... I've purged all the server side caches, but client side ones can still cause a problem.

Can you try going to the page doing a **Hard Refresh**? <kbd>Cmd + Shift + R</kbd> on mac, and <kbd>Ctrl + F5</kbd> on windows.

Alternatively, you can add `?force-pass` to the end, - https://nuzlocke.app/guides/platinum?force-pass=true - to force your browser to get the latest assets.

**Comment by MicheleStoltz** [comment]
> 

Hey!
Refreshing dint help but adding force-pass=true worked. Thanks :)
