### ISSUE TITLE
Transfer Save Bug

### ISSUE THREAD

**Issue by Sabber234** [domtronn/nuzlocke.app#120]
**Describe the bug**

**To Reproduce**
1. Go to 'Nuzlocke.app/saves'
2. Click on 'Transfer save'
3. The code won't be a code, but the following message:
4. 
<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

I've used the site for 2 nuzlockes (Pokémon Y and Pokémon Alpha Sapphire), and it has happened to both of them.

**Expected behavior**
I was supposed to be given a code to transfer my nuzlocke data.

**Screenshots**
![image](https://user-images.githubusercontent.com/59101176/235377535-347c81d3-3be1-4b25-bfbd-81dedcb0c90f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera
 - Version: The newest as of writing this

**Additional context**
I believe this happens when there is too much data stored in the nuzlocke. When I had only completed 2 gyms I got a completely fine code, but later on I got this error message instead.

**Comment by domtronn** [comment]
Hey @Sabber234 - thanks for raising, annoyingly this is a known issue which I think started when introducing the **Death Epitaph** feature... Although could have happened before

Since The epitaphs are long plain text strings which are added as query parameters, a lot of the hosting CDNs limit the request size before it even hits the servers 😕  I've considered filtering out this data, but that also feels not great since transferring would almost always cause data loss.

I've tried to configure the CDNs to allow larger headers/request URIs but they don't seem to adhere to the changes.

---

If you could go into the dev console and run the `window.nz.size()` command, and paste the results here that would be useful.

I'm also working on a feature to allow downloading & importing of save data to and from a file which should be ready later today. _(see #112 & #121)_

**Comment by domtronn** [comment]
@Sabber234 this should now be addressed.

I've done a fairly large refactor of the share functionality, and these limits shouldn't be encountered anymore!
It should also allow you to transfer saves with epitaphs in as well (see #123)
